### ISSUE TITLE
运行出错，SSL有问题

### ISSUE THREAD

**Issue by a641764137** [Goojoe/LTSC-ADD-Microsoft-Store#3]
运行记录如下：
Please select language:

1 English
2 简体中文
3 Français
4 日本語
5 Deutsch
6 Español
2
--------------------------------------
脚本名称:LTSC 微软商店 最新版下载脚本
Github项目地址:https://github.com/Goojoe/LTSC-ADD-Microsoft-Store
作者：咕咕乔
--------------------------------------
请选择架构(输入数字):
1 arm
2 arm64
3 x64
4 x86
:3
是否需要配置HTTP代理(y/n):
:y
请输入HTTP代理,例子:(127.0.0.1:1080):
127.0.0.1:7890
请求中,请等待,失败可尝试配置代理
Traceback (most recent call last):
  File "main.py", line 168, in <module>
  File "main.py", line 102, in download
  File "requests\api.py", line 115, in post
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 769, in urlopen
  File "urllib3\connectionpool.py", line 295, in _get_conn
  File "urllib3\connectionpool.py", line 1056, in _new_conn
ImportError: Can't connect to HTTPS URL because the SSL module is not available.
[10520] Failed to execute script 'main' due to unhandled exception!

**Comment by Goojoe** [comment]
这样的问题很常见，一般是你自己的网络问题。我刚才测试了，没有问题。你可以试试不配置HTTP代理是否可以下载。还有，你使用的是Releases 还是自己克隆仓库手动安装环境运行的？

**Comment by Goojoe** [comment]
你再试一下releases吧，这是pyinstaller的问题
